services:
  - type: web
    name: esante-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn esante_backend.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
